// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWjVNr-_UBmjc9U_2u6LF0F3fOyL1K2A',
    appId: '1:587655886115:web:627daf475ba700866dc896',
    messagingSenderId: '587655886115',
    projectId: 'quize-4aa9c',
    authDomain: 'quize-4aa9c.firebaseapp.com',
    storageBucket: 'quize-4aa9c.appspot.com',
    measurementId: 'G-6HYZ2S2LT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDltMoIGUSua9pyC9cEiyF6nZFvXz4GL8c',
    appId: '1:587655886115:android:d00cbc78c33095666dc896',
    messagingSenderId: '587655886115',
    projectId: 'quize-4aa9c',
    storageBucket: 'quize-4aa9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPymzB8kVPNh-RMeErjPqGT2SnB0V_LI',
    appId: '1:587655886115:ios:1481aea3471257886dc896',
    messagingSenderId: '587655886115',
    projectId: 'quize-4aa9c',
    storageBucket: 'quize-4aa9c.appspot.com',
    androidClientId: '587655886115-5jof93d4gce503air6p18639c13f2u75.apps.googleusercontent.com',
    iosClientId: '587655886115-3u4g72q453pv54s8b3gis8gvnkfg8h4r.apps.googleusercontent.com',
    iosBundleId: 'com.tdtu.da2.g60.whizz',
  );
}
